compatibility_date = "2024-06-01"
name = "saveoursouls-pages"
pages_build_output_dir = "dist"

# You can add default vars for local preview here (do not commit secrets in real projects)
[vars]
# RELAY_TOKEN = "dev-only-token"
# MAIL_FROM = "noreply@example.com"
# MAIL_FROM_NAME = "Save Our Souls"
# MAIL_SUBJECT = "SOS 警报：需要紧急关注"

[[kv_namespaces]]
binding = "SOS_KV"
# Fill in the following IDs after creating KV in Cloudflare dashboard (Pages > Settings > Functions > KV bindings)
id = ""
preview_id = ""
